#Iron Chests Default Files
#Setting a value will recopy the default files.
<<<<<<< HEAD
#Sun Aug 25 11:39:59 JST 2024
=======
#Sat Aug 24 18:16:07 MST 2024
>>>>>>> 7440d186 (Add pregen configs)
barrels=true
chests=true
chest_upgrades=true
