#Iron Chests Default Files
#Setting a value will recopy the default files.
#Sat Aug 24 21:04:51 MST 2024
=\=\=\=\=\=\=
barrels=true
chests=true
>>>>>>>=7440d186 (Add pregen configs)
chest_upgrades=true
<<<<<<<=HEAD
