//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//Don't touch me!
//#Add
recipes.addShaped(<weather2:tornado_siren>, [[<minecraft:iron_nugget>, <minecraft:noteblock>, <minecraft:iron_nugget>],[<minecraft:noteblock>, <minecraft:quartz>, <minecraft:noteblock>], [<minecraft:wool:15>, <minecraft:redstone>, <minecraft:wool:15>]]);
recipes.addShaped(<weather2:tornado_siren_manual>, [[<minecraft:iron_nugget>, <minecraft:noteblock>, <minecraft:iron_nugget>],[<minecraft:noteblock>, <minecraft:quartz>, <minecraft:noteblock>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<weather2:weather_forecast>, [[<minecraft:concrete:15>, <opencomputers:hologram1>, <minecraft:concrete:15>],[<minecraft:concrete:15>, <opencomputers:card:6>.withTag({RepairCost: 0, display: {Lore: ["§aThis particular Network Card is linked to the UCDF's", "§aAlfheim Reconnaisance Orbiter(ARO), allowing it", "§ato receive weather data."], Name: "ARO Network Card"}}).onlyWithTag({RepairCost: 0, display: {Lore: ["§aThis particular Network Card is linked to the UCDF's", "§aAlfheim Reconnaisance Orbiter(ARO), allowing it", "§ato receive weather data."], Name: "ARO Network Card"}}), <minecraft:concrete:15>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<weather2:tornado_sensor>, [[<minecraft:concrete:15>, <wrcbe:material:5>, <minecraft:concrete:15>],[<minecraft:concrete:15>, <opencomputers:card:6>.withTag({RepairCost: 0, display: {Lore: ["§aThis particular Network Card is linked to the UCDF's", "§aAlfheim Reconnaisance Orbiter(ARO), allowing it", "§ato receive weather data."], Name: "ARO Network Card"}}).onlyWithTag({RepairCost: 0, display: {Lore: ["§aThis particular Network Card is linked to the UCDF's", "§aAlfheim Reconnaisance Orbiter(ARO), allowing it", "§ato receive weather data."], Name: "ARO Network Card"}}), <minecraft:concrete:15>], [<minecraft:redstone>, <minecraft:redstone>, <minecraft:redstone>]]);
recipes.addShaped(<openblocks:fan>, [[null, <industrialforegoing:plastic>, null],[<industrialforegoing:plastic>, <industrialforegoing:plastic>, <industrialforegoing:plastic>], [null, <ore:circuitBasic>, null]]);
//File End
